[package]
name = "car-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.20.0"
image = "0.25.5"
rand = "0.8.5"
sdl2 = "0.37.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["sync"] }
wgpu = "23.0.0"
